Explicitpy include homedir-polyfill in requirements
Something changed upstream and it's no longer (it seems) included as a dependency for jest-puppeteer. This is causing an issue in tests:

Error: Jest: Got error running globalSetup ... reason: Cannot find module 'homedir-polyfill'

A failing test with this is https://github.com/Jonathonsun03/MUSA611-school-explorer/actions/runs/3231201183/jobs/5290471771